name: Prepare Release

on:
  push:
    branches:
      - mains

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Create or update release PR
        uses: changesets/action@v1
        with:
          version: npm run version
          commit: "chore: update versions"
          title: "Version Packages"
          setupGitUser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
